# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x13InitStrategyRequest\x12\x16\n\x0e\x42inaryLocation\x18\x01 \x01(\t\"\"\n\x14InitStrategyResponse\x12\n\n\x02ID\x18\x01 \x01(\t2F\n\x07Greeter\x12;\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x16.example.HelloResponse\"\x00\x32\x61\n\x0cStrategyPool\x12Q\n\x10InitStrategyPool\x12\x1c.example.InitStrategyRequest\x1a\x1d.example.InitStrategyResponse\"\x00\x42\x13Z\x11./example;exampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021./example;example'
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=54
  _globals['_HELLORESPONSE']._serialized_start=56
  _globals['_HELLORESPONSE']._serialized_end=88
  _globals['_INITSTRATEGYREQUEST']._serialized_start=90
  _globals['_INITSTRATEGYREQUEST']._serialized_end=135
  _globals['_INITSTRATEGYRESPONSE']._serialized_start=137
  _globals['_INITSTRATEGYRESPONSE']._serialized_end=171
  _globals['_GREETER']._serialized_start=173
  _globals['_GREETER']._serialized_end=243
  _globals['_STRATEGYPOOL']._serialized_start=245
  _globals['_STRATEGYPOOL']._serialized_end=342
# @@protoc_insertion_point(module_scope)
